#cloud-config
merge_how:
 - name: list
   settings: [append, no_replace]
 - name: dict
   settings: [no_replace, recurse_list]

write_files:
  - path: /opt/ceph/tls/ca.crt
    owner: root:root
    permissions: "0400"
    content: |
      ${indent(6, tls.ca_cert)}
  - path: /opt/ceph/tls/server.crt
    owner: root:root
    permissions: "0400"
    content: |
      ${indent(6, tls.server_cert)}
  - path: /opt/ceph/tls/server.key
    owner: root:root
    permissions: "0400"
    content: |
      ${indent(6, tls.server_key)}
  - path: /opt/ceph/ssh/ssh_key.pub
    owner: root:root
    permissions: "0400"
    content: |
      ${indent(6, ssh.public_key)}
  - path: /opt/ceph/ssh/ssh_key
    owner: root:root
    permissions: "0400"
    content: |
      ${indent(6, ssh.private_key)}
  - path: /opt/ceph/conf/services.yml
    owner: root:root
    permissions: "0500"
    content: |
      ---
      service_type: mon
      service_name: mon
      placement:
        count: 3
        label: "mon"
      ---
      service_type: mgr
      service_name: mgr
      networks:
        - ${public_network}
      placement:
        count: 2
        label: "mgr"
  - path: /opt/ceph/conf/hosts.yml
    owner: root:root
    permissions: "0500"
    content: |
%{ for node in ceph_cluster ~}
      ---
      service_type: host
      hostname: ${node.domain}
      addr: ${node.ip}
      labels:
%{ if node.monitor ~}
        - mon
%{ endif ~}
%{ if node.manager ~}
        - mgr
%{ endif ~}
%{ if node.osd ~}
        - osd
%{ endif ~}
%{ if node.admin ~}
        - _admin
%{ endif ~}
%{ endfor ~}
  - path: /opt/ceph/scripts/bootstrap.sh
    owner: root:root
    permissions: "0500"
    content: |
      cephadm bootstrap --mon-ip ${self_ip} \
                        --allow-fqdn-hostname \
                        --ssh-user ubuntu \
                        --dashboard-key /opt/ceph/tls/server.key \
                        --dashboard-crt /opt/ceph/tls/server.crt \
                        --ssh-private-key /opt/ceph/ssh/ssh_key \
                        --ssh-public-key /opt/ceph/ssh/ssh_key.pub
      ceph orch host add $(hostname) --labels=mon
      ceph orch host add $(hostname) --labels=mgr
      ceph orch apply -i /opt/ceph/conf/services.yml
  - path: /opt/ceph/scripts/expand.sh
    owner: root:root
    permissions: "0500"
    content: |
      ceph orch apply -i /opt/ceph/conf/hosts.yml

runcmd:
  - wget https://download.ceph.com/rpm-18.2.0/el9/noarch/cephadm
  - chmod +x cephadm
  - ./cephadm add-repo --release reef
  - ./cephadm install
  - rm cephadm
  - cephadm install ceph-common
